{
 "title": "Managed Services - ODF Service Level Overview",
 "description": "Dashboard depicting Service Level Indicators and Objectives for the ODF Managed Services offering.",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" },
   {
    "name": "provider_cluster",
    "label": "Provider cluster ID",
    "query": {
     "query": "label_values(subscription_sync_total{name=\"addon-ocs-provider\"}, _id)"
    }
   },
   {
    "name": "consumer_cluster",
    "label": "Consumer cluster ID",
    "query": {
     "query": "label_values(subscription_sync_total{name=\"addon-ocs-consumer\"}, _id)"
    }
   },
   { "name": "datasource", "label": "Data source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Fleet view",
   "type": "table",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count by(name) (subscription_sync_total{name=~\"addon-ocs-(provider|consumer)\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Provider", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "# For the \"total # of firing alerts\" tab.\ncount by (_id) (alerts{_id=~\"$provider_cluster.*\", alertstate=\"firing\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "# For the \"In breach\" tab.\nalerts{_id=~\"$provider_cluster.*\", alertname=~\"(CephMonQuorumLost|CephClusterErrorState)\", alertstate=\"firing\"} or vector(1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clusters in breach (28d)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 5 },
   "targets": [
    {
     "expr": "sum(group by (_id) (alerts{_id=~\"$provider_cluster.*\", alertname=~\"(CephMonQuorumLost|CephClusterErrorState)\", alertstate=\"firing\"})) or vector(0)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Consumer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "# For the \"total # of firing alerts\" tab.\ncount by (_id) (alerts{_id=~\"$consumer_cluster.*\", alertstate=\"firing\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "# For the \"In breach\" tab.\n# APIRemovedInNextEUSReleaseInUse is only for demonstration purposed and will be removed.\nalerts{_id=~\"$consumer_cluster.*\", alertname=~\"(CephMonQuorumLost|CephClusterErrorState)\", alertstate=\"firing\"} or vector(1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clusters in breach (28d)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 13 },
   "targets": [
    {
     "expr": "sum(group by (_id) (alerts{_id=~\"$consumer_cluster.*\", alertname=~\"(CephMonQuorumLost|CephClusterErrorState)\", alertstate=\"firing\"})) or vector(0)",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}